-- Generated by nwg-displays on 2026-06-18 at 14:37:28. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "desc:AOC 2481W ANSJ89A001341",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "desc:Chimei Innolux Corporation 0x1409",
    default = true
})
hl.workspace_rule({
    workspace = "3",
    monitor = "desc:AOC 2481W AJEJ19A008716",
    default = true
})
