alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias q='exit'
alias cls='clear'
alias pg='ping google.com'
alias meowsql='/opt/meowsql/meowsql.appimage'
alias android='/opt/android-studio/bin/studio.sh'
alias kbbi='kbbi-shell'
alias osu='/opt/osu/osu.AppImage'
alias filezilla='/opt/FileZilla3/bin/filezilla'
alias postman='/opt/Postman/Postman'
alias sd="cd ~ && cd \$(find * -type d | fzf)"
alias sad="cd ~ && cd \$(find . -type d | fzf)"
