alias sudo='sudo '
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias q='exit'
alias cls='clear'
alias pg='ping google.com'
alias meowsql='/opt/meowsql/meowsql.appimage'
# alias android='/opt/android-studio/bin/studio.sh'
alias kbbi='kbbi-shell'
alias osu='/opt/osu/osu.AppImage'
alias filezilla='/opt/FileZilla3/bin/filezilla'
alias postman='/opt/Postman/Postman'
alias sd="cd ~ && cd \$(find * -type d -not -path 'Android/Sdk/*' -not -path 'Development/*' -not -path '*/node_modules/*' -not -path '*/vendor/*' -not -path '*/.git/*'| fzf)"
alias sdp="cd ~/Documents/Programming && cd \$(find * -type d -not -path '*/node_modules/*' -not -path '*/vendor/*' -not -path '*/.*/*'| fzf)"
alias sad="cd ~ && cd \$(find . -type d | fzf)"
alias nvim="/opt/nvim/nvim.appimage"
alias ccc="xclip -sel clip"
alias emu="emulator -avd Pixel_4a_API_34 -ranchu"
alias phpserve="php -S 127.0.0.1:8000 -t public"
