-- Generated by nwg-displays on 2026-10-05 at 12:44:04. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "desc:AOC 2481W ANSJ69A000029",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "desc:Chimei Innolux Corporation 0x1409",
    default = true
})
hl.workspace_rule({
    workspace = "3",
    monitor = "desc:AOC 2481W ANSJ89A001336",
    default = true
})
