# =======================
# Zsh options
# =======================
setopt correct
# echo 'unset HISTFILE' >>|${ZDOTDIR:-~}/.zshrc

# =======================
# Oh My Zsh
# =======================
export ZSH="$HOME/.oh-my-zsh"
source $ZSH/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh

ZSH_THEME="" # repo-local, sourced below from $DOTFILES_PATH/omz/themes
CATPPUCCIN_FLAVOR="mocha"
CATPPUCCIN_SHOW_TIME=true

plugins=(
  git
  flutter
  laravel
  tmux
  vi-mode
  gcloud
  kubectl
  podman
  docker-compose
  zsh-autocomplete
  zsh-autosuggestions
  zsh-syntax-highlighting
)

export ZSH_TMUX_AUTONAME_SESSION=true

if [[ -d "$ZSH" ]]; then
  source "$ZSH/oh-my-zsh.sh"
fi

if [[ -n "$DOTFILES_PATH" ]]; then
  source "$DOTFILES_PATH/omz/themes/catppuccin.zsh-theme"
else
  echo "[zshrc] DOTFILES_PATH unset, catppuccin theme not loaded" >&2
fi

. "$ZSH_CUSTOM/plugins/catppuccin-zsh-syntax-highlighting/themes/catppuccin_mocha-zsh-syntax-highlighting.zsh"

# =======================
# Load aliases
# =======================
if [[ -n "$DOTFILES_PATH" && -f "$DOTFILES_PATH/config/.aliases" ]]; then
  source "$DOTFILES_PATH/config/.aliases"
fi

# =======================
# yazi (cwd integration)
# =======================
y() {
  local tmp cwd
  tmp="$(mktemp -t yazi-cwd.XXXXXX)" || return

  yazi "$@" --cwd-file="$tmp"

  if cwd="$(<"$tmp")" && [[ -n "$cwd" && "$cwd" != "$PWD" ]]; then
    builtin cd "$cwd"
  fi

  rm -f "$tmp"
}

# =======================
# Tool integrations
# =======================

# Mise
if command -v mise >/dev/null 2>&1; then
  eval "$(mise activate zsh)"
fi

# Jump
if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init zsh)"
fi

# rust
[[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"

# Fzf
source <(fzf --zsh)

# Crossplane
if command -v crossplane >/dev/null 2>&1; then
  source <(crossplane completions)
fi

# Helm
if command -v helm >/dev/null 2>&1; then
  source <(helm completion zsh)
fi

# Terraform
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/terraform terraform

# =======================
# Shell completions
# =======================
# Static completions from /usr/share/zsh/site-functions (pacman, yay, yazi,
# zoxide, eza, fd, rg, bat, ...) are already autoloaded via $fpath. The blocks
# below explicitly source completions generated by tools that ship them.

# Docker / Podman (docker is the podman-docker shim, so register podman's
# completion for both command names)
if command -v podman >/dev/null 2>&1; then
  source <(podman completion zsh)
  if command -v docker >/dev/null 2>&1; then
    compdef _podman docker 2>/dev/null
  fi
fi

# kubectl
if command -v kubectl >/dev/null 2>&1; then
  source <(kubectl completion zsh)
fi

# GitHub CLI
if command -v gh >/dev/null 2>&1; then
  source <(gh completion -s zsh)
fi

# uv
if command -v uv >/dev/null 2>&1; then
  source <(uv generate-shell-completion zsh)
fi

# Bun
if command -v bun >/dev/null 2>&1; then
  source <(bun completions)
fi

# Rustup
if command -v rustup >/dev/null 2>&1; then
  source <(rustup completions zsh)
  source <(rustup completions zsh cargo)
fi

# Mise
if command -v mise >/dev/null 2>&1; then
  source <(mise completion zsh)
fi

# GO fix
if command -v go >/dev/null 2>&1; then
  export PATH="$(go env GOBIN):$PATH"
fi

# Private Shell
unset HISTFILE
# export HISTSIZE=0
# export SAVEHIST=0
