-- Generated by nwg-displays on 2026-09-07 at 15:10:35. Do not edit manually.

hl.monitor({
    output = "desc:Chimei Innolux Corporation 0x1409",
    mode = "1920x1080@60.01",
    position = "1920x0",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "desc:AOC 2481W AJEJ19A008716",
    mode = "1920x1080@60.0",
    position = "3840x0",
    scale = 1,
    vrr = 0
})
hl.monitor({
    output = "desc:AOC 2481W ANSJ89A001341",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1,
    vrr = 0
})
