"Boot with standard options"  "root=/dev/nvme0n1p3 rw add_efi_memmap quiet psmouse.synaptics_intertouch=1 i915.enable_dc=0 i915.enable_psr=0 i2c_hid.polling_mode=1"
"Boot to single-user mode"    "root=/dev/nvme0n1p3 rw add_efi_memmap quiet psmouse.synaptics_intertouch=1 i915.enable_dc=0 i915.enable_psr=0 i2c_hid.polling_mode=1 single"
"Boot with minimal options"   "ro root=/dev/nvme0n1p3"
