timeout 3
use_nvram false

# Display & IO
include themes/catppuccin/mocha.conf
resolution 1920 1080
enable_touch
enable_mouse
mouse_speed 5

#showtools shell, bootorder, gdisk, memtest, mok_tool, apple_recovery, windows_recovery, about, hidden_tags, reboot, exit, firmware, fwupdate
extra_kernel_version_strings "linux-hardened,linux-rt-lts,linux-zen,linux-lts,linux-rt,linux"
