#: Fonts
font_size 10.0
font_family GeistMono NF SemiBold

#: Window
background_opacity 0.8
confirm_os_window_close 0

# Cursor Trail
cursor_trail 3
cursor_trail_decay 0.1 0.4

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
