-- SUPER KEY
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mainMod = "SUPER"
local HOME = os.getenv("HOME")
local waybar = HOME .. "/.config/waybar"
local scripts = HOME .. "/.config/hypr/scripts"

-- Applications
local terminal = "kitty"
local browser = "zen-browser"
local fileManager = "dolphin"
local menu = "hyprlauncher"

-- Windows control --------------------------------------------------------------------------------------

-- Commands
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exec_cmd("hyprctl activewindow | grep pid | tr -d 'pid:' | xargs kill"))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + M", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mainMod .. " + T", hl.dsp.window.float({ action = "toggle" }))
-- TODO: manual review on line 21 — no mapping for dispatcher "workspaceopt"
-- hl.bind(mainMod .. " + SHIFT + T", hl.dsp.workspaceopt("allfloat"))

-- Move focus
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))

hl.bind("ALT + Tab", hl.dsp.window.cycle_next({ next = true }))

-- Resize
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.resize({ x = -50, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.resize({ x = 50, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.resize({ x = 0, y = -50, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.resize({ x = 0, y = 50, relative = true }), { repeating = true })

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

-- Swap window
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.layout("swapsplit"))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.layout("swapsplit"))

hl.bind(mainMod .. " + ALT + left", hl.dsp.window.swap({ direction = "l" }))
hl.bind(mainMod .. " + ALT + right", hl.dsp.window.swap({ direction = "r" }))
hl.bind(mainMod .. " + ALT + up", hl.dsp.window.swap({ direction = "u" }))
hl.bind(mainMod .. " + ALT + down", hl.dsp.window.swap({ direction = "d" }))

hl.bind(mainMod .. " + ALT + H", hl.dsp.window.swap({ direction = "l" }))
hl.bind(mainMod .. " + ALT + L", hl.dsp.window.swap({ direction = "r" }))
hl.bind(mainMod .. " + ALT + J", hl.dsp.window.swap({ direction = "d" }))
hl.bind(mainMod .. " + ALT + K", hl.dsp.window.swap({ direction = "u" }))

-- Groups
hl.bind(mainMod .. " + G", hl.dsp.group.toggle())
-- TODO: manual review on line 64 — changegroupactive: expected 'f', 'b', or an index (got "")
-- hl.bind("ALT + tab", hl.dsp.changegroupactive())

-- Workspaces -----------------------------------------------------------------------------

-- Jump to workspace x
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

-- Move active window and follo workspaces
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))
hl.bind(mainMod .. " + SHIFT + bracketleft", hl.dsp.window.move({ workspace = -1 }))
hl.bind(mainMod .. " + SHIFT + bracketright", hl.dsp.window.move({ workspace = "+1" }))

-- Move active window to a workspace silently
hl.bind(mainMod .. " + CTRL + 1", hl.dsp.window.move({ workspace = 1, follow = false }))
hl.bind(mainMod .. " + CTRL + 2", hl.dsp.window.move({ workspace = 2, follow = false }))
hl.bind(mainMod .. " + CTRL + 3", hl.dsp.window.move({ workspace = 3, follow = false }))
hl.bind(mainMod .. " + CTRL + 4", hl.dsp.window.move({ workspace = 4, follow = false }))
hl.bind(mainMod .. " + CTRL + 5", hl.dsp.window.move({ workspace = 5, follow = false }))
hl.bind(mainMod .. " + CTRL + 6", hl.dsp.window.move({ workspace = 6, follow = false }))
hl.bind(mainMod .. " + CTRL + 7", hl.dsp.window.move({ workspace = 7, follow = false }))
hl.bind(mainMod .. " + CTRL + 8", hl.dsp.window.move({ workspace = 8, follow = false }))
hl.bind(mainMod .. " + CTRL + 9", hl.dsp.window.move({ workspace = 9, follow = false }))
hl.bind(mainMod .. " + CTRL + 0", hl.dsp.window.move({ workspace = 10, follow = false }))
hl.bind(mainMod .. " + CTRL + bracketleft", hl.dsp.window.move({ workspace = -1, follow = false }))
hl.bind(mainMod .. " + CTRL + bracketright", hl.dsp.window.move({ workspace = "+1", follow = false }))

-- Cycle workspace
hl.bind(mainMod .. " + Tab", hl.dsp.focus({ workspace = "m+1" }))
hl.bind(mainMod .. " + SHIFT + Tab", hl.dsp.focus({ workspace = "m-1" }))
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + CTRL + down", hl.dsp.focus({ workspace = "empty" }))

-- Special workspace
hl.bind(mainMod .. " + SHIFT + U", hl.dsp.window.move({ workspace = "special" }))
hl.bind(mainMod .. " + U", hl.dsp.workspace.toggle_special(""))

-- Fn keys/ Scripts -------------------------------------------------------------------------

-- Display
hl.bind(
	mainMod .. " + SHIFT + mouse_down",
	hl.dsp.exec_cmd(
		"hyprctl keyword cursor:zoom_factor $(awk \"BEGIN {print $(hyprctl getoption cursor:zoom_factor | grep 'float:' | awk '{print $2}') + 0.5}\")"
	)
)
hl.bind(
	mainMod .. " + SHIFT + mouse_up",
	hl.dsp.exec_cmd(
		"hyprctl keyword cursor:zoom_factor $(awk \"BEGIN {print $(hyprctl getoption cursor:zoom_factor | grep 'float:' | awk '{print $2}') - 0.5}\")"
	)
)
hl.bind(mainMod .. " + SHIFT + Z", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor 1"))

-- Launcher
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind("ALT + SPACE", hl.dsp.exec_cmd("pkill rofi || rofi -show drun -modi drun,filebrowser,run,window"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(scripts .. "/wallpaperSelect.sh"))
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd(scripts .. "/clipManager.sh"))

-- Screenshoot keybindings
hl.bind("ALT + SHIFT + 5", hl.dsp.exec_cmd('grim -g "$(slurp)" - | wl-copy'))
hl.bind("CTRL + ALT + SHIFT + 5", hl.dsp.exec_cmd("grim"))
hl.bind("Print", hl.dsp.exec_cmd("grim"))

-- Brightness Control
hl.bind(
	"XF86MonBrightnessUp",
	hl.dsp.exec_cmd(
		'brightnessctl -q s +5% && notify-send -t 1000 -h string:x-canonical-private-synchronous:brightness "Brightness" "$(brightnessctl -m | awk -F, \'{print $4}\')"'
	)
)
hl.bind(
	"XF86MonBrightnessDown",
	hl.dsp.exec_cmd(
		'brightnessctl -q s 5%- && notify-send -t 1000 -h string:x-canonical-private-synchronous:brightness "Brightness" "$(brightnessctl -m | awk -F, \'{print $4}\')"'
	)
)

-- Sound Control
hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd(
		'wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+ && notify-send -t 1000 -h string:x-canonical-private-synchronous:volume "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk \'{vol=int($2*100); muted=$3=="[MUTED]"?1:0; if(muted) print vol"% (MUTED)"; else print vol"%";}\')"'
	)
)
hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd(
		'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && notify-send -t 1000 -h string:x-canonical-private-synchronous:volume "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk \'{vol=int($2*100); muted=$3=="[MUTED]"?1:0; if(muted) print vol"% (MUTED)"; else print vol"%";}\')"'
	)
)
hl.bind(
	"XF86AudioMute",
	hl.dsp.exec_cmd(
		'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && notify-send -t 1000 -h string:x-canonical-private-synchronous:volume "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk \'{vol=int($2*100); muted=$3=="[MUTED]"?1:0; if(muted) print "MUTED ("vol"%)"; else print vol"%";}\')"'
	)
)
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("pactl set-source-mute @DEFAULT_SOURCE@ toggle"))

-- Player
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl pause"))
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

-- Lock
hl.bind(mainMod .. " + code:9", hl.dsp.exec_cmd("wlogout"))
hl.bind("XF86PowerOff", hl.dsp.exec_cmd("hyprlock"))

-- Reload
hl.bind(mainMod .. " + CTRL + R", hl.dsp.exec_cmd("hyprctl reload"))
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd(waybar .. "/launch.sh"))
hl.bind("CTRL + ALT + Delete", hl.dsp.exit())
